// <auto-generated />
namespace CasgemCodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig_relation_guide_SocialMedia : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_relation_guide_SocialMedia));
        
        string IMigrationMetadata.Id
        {
            get { return "202307120809075_mig_relation_guide_SocialMedia"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
